---
- hosts: all
  remote_user: vagrant 
  sudo: yes
  tasks:
  - group: name=devops state=present
  - name: create devops user with admin previleges
    user: name=devops comment="Devops User" uid=2001 group=devops
  - name: install htop package
    acrtion: apt name=htop state=present update_cache=yes

- hosts: www
  user: vagrant
  sudo: yes
  tasks:
  - name: add official nginx repository
    apt_repository: repo='deb http://nginx.org/packages/ubuntu/ lucid nginx'
  - name: install nginx web server and ensure its at the latest version
    apt: name=nginx state=latest
  - name: 
    service: name=nginx state=started
